/**
 * One sidebar per root section. Each section opens on a generated landing
 * page (cards) and lists the section's folder in docs/.
 */

/** Build a root section: a landing page plus the folder's autogenerated tree. */
function section(label, dirName, description) {
  return [
    {
      type: 'category',
      label,
      collapsible: false,
      link: {type: 'generated-index', slug: `/${dirName}`, title: label, description},
      items: [{type: 'autogenerated', dirName}],
    },
  ];
}

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  guideSidebar: section('Guide', 'guide',
    'For end users and consultants: find your way around iDempiere and configure it for a business.'),
  installSidebar: section('Install & upgrade', 'install',
    'For system administrators: install and run an iDempiere server, and upgrade it to a new version.'),
  developSidebar: section('Develop', 'develop',
    'For developers: extend iDempiere with OSGi plugins, from setting up your environment to shipping the plugin, and contribute to iDempiere core.'),
  integrateSidebar: section('Integrate', 'integrate',
    'For developers: connect other applications and frontends to iDempiere.'),
  pluginsSidebar: section('Plugins', 'plugins',
    'Ready-made extensions and 2Packs that you can install on iDempiere.'),
  releaseNotesSidebar: section('Release notes', 'release-notes',
    'What changed in each iDempiere release. To plan an upgrade, use the Compare versions page.'),
};

module.exports = sidebars;
